name: Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Emscripten SDK
      uses: trzeci/emscripten@v2.0.17

    - name: Build
      run: |
        bash build.sh

    - name: Upload To Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        user_name: 'GitHub Actions'
        user_email: '

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
    - uses: trzeci/emscripten
    - name: Build
      run: |
        npm install
        bash build.sh
    - uses: actions/configure-pages@v4
    - uses: actions/upload-pages-artifact@v3
      with:
        path: 'dist'
    - uses: actions/deploy-pages@v4
      id: deployment
